general {
    lock_cmd = pidof hyprlock || hyprlock       # команда для блокировки
    before_sleep_cmd = loginctl lock-session    # заблокировать перед сном
    after_sleep_cmd = hyprctl dispatch dpms on  # включить монитор после пробуждения
}

listener {
    timeout = 300                                # 5 минут (300 секунд)
    on-timeout = loginctl lock-session           # блокируем экран
}

listener {
    timeout = 330                                # 5.5 минут
    on-timeout = hyprctl dispatch dpms off       # выключаем монитор для экономии
    on-resume = hyprctl dispatch dpms on         # включаем обратно при движении
}
