general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/gleb/Изображения/Wallpapers/forest.jpg
    color = rgba(10, 20, 10, 1.0)
    blur_passes = 3 
    blur_size = 7
    brightness = 0.5
}

# ЧАСЫ
label {
    monitor =
    text = $TIME
    color = rgba(180, 220, 180, 0.8)
    font_size = 96
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 160
    halign = center
    valign = center
}

# РАСКЛАДКА (RU/EN)
label {
    monitor =
    text = $LAYOUT
    color = rgba(180, 220, 180, 0.6)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

# ПОЛЕ ВВОДА
input-field {
    monitor =
    size = 420, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(40, 70, 40, 0.5)
    inner_color = rgba(15, 25, 15, 0.7)
    font_color = rgb(180, 220, 180)
    fade_on_empty = false
    placeholder_text = <span foreground="##5e7d5e">Вводи пароль сука ебаная.</span>
    hide_input = false
    check_color = rgba(100, 200, 100, 1.0)
    fail_color = rgba(200, 50, 50, 1.0)
    position = 0, -50
    halign = center
    valign = center
}
